
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vision_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "5432:5432"

  # qdrant:
  #   image: qdrant/qdrant
  #   ports:
  #     - "6333:6333"
  #   volumes:
  #     - qdrant_data:/qdrant/storage
    
  auth-service:
    build: ./apps/auth-service
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - JWT_SECRET=your_jwt_secret
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:password@postgres:5432/vision_db
      - FRONTEND_URL=http://localhost:5173
    networks:
      - backend
    depends_on:
      - postgres

  image-service:
    build: ./apps/image-service
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - JWT_SECRET=your_jwt_secret
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:password@postgres:5432/vision_db
    volumes:
      - image_data:/app/uploads
    networks:
      - backend
    depends_on:
      - postgres
  
  gallery-service:
    build: ./apps/gallery-service
    environment:
      - PORT=5003
      - DATABASE_URL=postgresql://user:password@db:5432/gallerydb?schema=public
      - JWT_SECRET=your_jwt_secret_key_here
    ports:
      - "5003:5003"
    networks:
      - backend
    depends_on:
      - postgres

  # face-service:
  #   build: ./apps/face-service
  #   ports:
  #     - "5004:5004"
  #   environment:
  #     - PORT=5003
  #     - JWT_SECRET=your_jwt_secret
  #     - PYTHON_ENV=development
  #     - DATABASE_URL=postgres://postgres:password@postgres:5432/vision_db
  #     - QDRANT_URL=http://qdrant:6333
  #     - QDRANT_HOST=qdrant
  #   depends_on:
  #     - qdrant

  gateway:
    build: ./gateway
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=development
    networks:
      - backend
    depends_on:
      - auth-service
      - image-service
      # - face-service

volumes:
  pgdata:
  image_data:
  # qdrant_data:

networks:
  backend:
