
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vision_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    
  auth-service:
    build: ./apps/auth-service
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - JWT_SECRET=your_jwt_secret
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:password@postgres:5432/vision_db
      - FRONTEND_URL=http://localhost:5173
    depends_on:
      - postgres

  image-service:
    build: ./apps/image-service
    ports:
      - "5002:5002"
    volumes:
      - ./image:/app
      - image_data:/app/uploads
    environment:
      - PORT=5002
      - JWT_SECRET=your_jwt_secret
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:password@postgres:5432/vision_db
    depends_on:
      - postgres

  face-service:
    build: ./apps/face-service
    ports:
      - "5003:5003"
    environment:
      - PORT=5003
      - JWT_SECRET=your_jwt_secret
      - PYTHON_ENV=development
      - DATABASE_URL=postgres://postgres:password@postgres:5432/vision_db
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_HOST=qdrant
    depends_on:
      - qdrant

volumes:
  pgdata:
  image_data:
  qdrant_data:
