export const mockUsers = [
  { id: 1, name: "John Doe", email: "john@example.com", canUpload: true },
  { id: 2, name: "Jane Smith", email: "jane@example.com", canUpload: true },
  { id: 3, name: "Robert Johnson", email: "robert@example.com", canUpload: false },
  { id: 4, name: "Emily Davis", email: "emily@example.com", canUpload: true },
  { id: 5, name: "Michael Wilson", email: "michael@example.com", canUpload: false },
]

export const mockImages = [
  {
    id: 1,
    title: "Mountain Landscape",
    photographer: "John Doe",
    isPublic: true,
    tags: ["nature", "mountain"],
    url: "/placeholder.svg?height=300&width=400",
  },
  {
    id: 2,
    title: "City Skyline",
    photographer: "Jane Smith",
    isPublic: false,
    tags: ["city", "architecture"],
    url: "/placeholder.svg?height=300&width=400",
  },
  {
    id: 3,
    title: "Beach Sunset",
    photographer: "Robert Johnson",
    isPublic: true,
    tags: ["beach", "sunset"],
    url: "/placeholder.svg?height=300&width=400",
  },
  {
    id: 4,
    title: "Forest Path",
    photographer: "Emily Davis",
    isPublic: false,
    tags: ["nature", "forest"],
    url: "/placeholder.svg?height=300&width=400",
  },
  {
    id: 5,
    title: "Desert Dunes",
    photographer: "Michael Wilson",
    isPublic: true,
    tags: ["nature", "desert"],
    url: "/placeholder.svg?height=300&width=400",
  },
  {
    id: 6,
    title: "Waterfall",
    photographer: "John Doe",
    isPublic: false,
    tags: ["nature", "water"],
    url: "/placeholder.svg?height=300&width=400",
  },
  {
    id: 7,
    title: "Northern Lights",
    photographer: "Jane Smith",
    isPublic: true,
    tags: ["night", "sky"],
    url: "/placeholder.svg?height=300&width=400",
  },
  {
    id: 8,
    title: "Snowy Mountains",
    photographer: "Robert Johnson",
    isPublic: false,
    tags: ["nature", "snow"],
    url: "/placeholder.svg?height=300&width=400",
  },
]
